import CodeBlock from "@/components/Articles/CodeBlock";
import { Article } from "@/types";

export const meta: Article = {
  id: 38,
  slug: "dspy-production-optimizing-ai-agents-2026",
  title:
    "DSPy 3 in production 2026: programming AI agents with signatures, modules, and optimizers",
  excerpt:
    "How Stanford's DSPy went from a research paper on self-improving pipelines to a production framework running at Shopify, Databricks, Dropbox, JetBlue, Moody's, Replit, and AWS. Covers the signature and module model, the four optimizers that ship in 3.0 (MIPROv2, SIMBA, GRPO, and the ICLR 2026 GEPA), MLflow 3 tracing, FastAPI async and streaming deployments, and the honest trade-offs against LangChain and LlamaIndex.",
  metaDescription:
    "A practical, technical guide to DSPy 3 for production AI agents in 2026. Covers signatures and modules, ChainOfThought and ReAct, the four optimizers (MIPROv2, SIMBA, GRPO, GEPA), MLflow 3 tracing, FastAPI asyncify and streamify deployments, the JetBlue and Databricks case study, structured outputs with BAMLAdapter and Pydantic, and the honest trade-offs versus LangChain and LlamaIndex.",
  image:
    "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=2400&q=80",
  author: {
    name: "Reactify Solutions",
    image: "/icon.png",
    designation: "Engineering Team",
  },
  tags: [
    "AI",
    "Agents",
    "DSPy",
    "Stanford",
    "LLM",
    "MLflow",
    "GEPA",
    "MIPROv2",
    "Production",
    "Databricks",
    "Optimization",
  ],
  publishDate: "2026-08-09",
  readingTime: "17 min read",
};

export default function DspyProductionOptimizingAiAgents2026Post() {
  return (
    <div className="prose prose-lg prose-invert max-w-none text-white/80">
      <p className="mb-6 text-lg leading-relaxed">
        DSPy started as a Stanford paper in late 2023 with a
        simple pitch: stop writing prompts by hand, and write
        Python programs that get compiled into prompts by an
        optimizer. Three years later the framework is running
        in production at Shopify, Databricks, Dropbox,
        JetBlue, Moody&rsquo;s, Replit, AWS, Sephora, and
        VMware. The 3.0 release in August 2025 added four
        strong optimizers, MLflow 3 tracing, and a stable
        deployment story with FastAPI, async, and streaming.
        The July 2025 GEPA paper, accepted as an oral at
        ICLR 2026, showed a reflective prompt optimizer that
        beats reinforcement learning by 20% with 35 times
        fewer rollouts. This article is how we ship DSPy
        agents on client work: the signature-and-module
        model, the four optimizers and when to reach for
        each, the MLflow 3 deployment path, and the honest
        trade-offs against LangChain and LlamaIndex.
      </p>

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        Why DSPy matters in 2026
      </h2>
      <p className="mb-6 leading-relaxed">
        Most AI agent code still looks like a giant string
        of prompt text with a few Python variables plugged
        in. That string is the whole program. It carries
        the task description, the tool schemas, the
        few-shot examples, the output format, and the
        safety rules. Every model swap breaks it. Every
        new tool changes it. Every eval run needs a human
        to guess what to change next. Teams call this
        prompt engineering. What it really is: a hand-tuned
        machine-learning system with no gradient signal, no
        version control that maps to behaviour, and no way
        to compare two changes without running the whole
        eval by hand.
      </p>
      <p className="mb-6 leading-relaxed">
        DSPy replaces the string with a Python program. You
        declare the shape of the task as a{" "}
        <strong>signature</strong> (typed inputs and
        outputs, a docstring for the task), pick a{" "}
        <strong>module</strong> that decides how the language
        model is called (ChainOfThought, ReAct, CodeAct,
        Refine), and compose modules like normal functions.
        The prompt text is generated by an{" "}
        <strong>adapter</strong> at runtime. An{" "}
        <strong>optimizer</strong> then rewrites the prompt,
        the few-shot examples, or even the model weights
        against a metric you define. The compiled artefact
        is a Python object you can save, load, version, and
        serve. That shape is the reason DSPy has crossed
        from research demo to a framework that ships real
        systems.
      </p>

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        The 2023 to 2026 timeline
      </h2>
      <ul className="mb-6 list-disc space-y-2 pl-6">
        <li>
          <strong>October 2023</strong>: The DSPy paper is
          published on arxiv (2310.03714){" "}
          <em>
            DSPy: Compiling Declarative Language Model Calls
            into Self-Improving Pipelines
          </em>{" "}
          by Omar Khattab and colleagues at Stanford. First
          proof that a compiled pipeline of LM calls can
          outperform hand-written prompts.
        </li>
        <li>
          <strong>June 2024</strong>: MIPROv2 (Multi-prompt
          Instruction Proposal Optimizer, version 2) is
          released. Combines instruction proposal, few-shot
          bootstrapping, and Bayesian optimization to pick
          the best prompt configuration. Becomes the default
          production optimizer for the next year.
        </li>
        <li>
          <strong>July 2024</strong>: The Databricks and
          JetBlue write-up{" "}
          <em>Optimizing Databricks LLM Pipelines with DSPy</em>{" "}
          ships. First widely-shared production case study.
          JetBlue reports a 2x faster deployment of a
          RAG-powered predictive maintenance chatbot
          compared to their previous LangChain pipeline.
        </li>
        <li>
          <strong>February 2025</strong>: DSPy 2.6 lands with
          native streaming and asynchronous execution
          support. Removes the last blocker for high-QPS
          FastAPI deployments.
        </li>
        <li>
          <strong>July 2025</strong>: The GEPA paper
          (arxiv 2507.19457) is published. A reflective
          prompt optimizer that samples full system
          trajectories, reflects on them in natural
          language, and evolves a Pareto tree of prompts.
          Beats MIPROv2 by 13% and GRPO by 20% with 35 times
          fewer rollouts.
        </li>
        <li>
          <strong>August 12, 2025</strong>: DSPy 3.0 ships.
          Four optimizers (MIPROv2, SIMBA, GRPO, GEPA),
          adapters (ChatAdapter, JSONAdapter, XMLAdapter,
          BAMLAdapter), multi-modal I/O with{" "}
          <code>dspy.Image</code> and <code>dspy.Audio</code>,
          native MLflow 3 tracing, and a stable save and
          load API. First release that a working
          production team can adopt without pinning to a
          commit.
        </li>
        <li>
          <strong>October 2025</strong>: DSPy 3.2 adds the
          Arbor RL trainer for GRPO, tighter LiteLLM
          integration, and MCP client support so any DSPy
          module can call an MCP server as a tool.
        </li>
        <li>
          <strong>March 2026</strong>: DSPy 3.3 introduces{" "}
          <code>dspy.Flex</code>, a module that lets GEPA
          restructure the program itself (add or remove
          steps, swap modules) not just the prompts inside
          it. First step towards program synthesis on top of
          prompt optimization.
        </li>
        <li>
          <strong>April 2026</strong>: The GEPA paper is
          presented as an oral at ICLR 2026. The
          reflective-over-RL result becomes the default read
          on why textual gradients beat scalar rewards for
          most production LLM tasks.
        </li>
      </ul>

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        The three primitives: signatures, modules, optimizers
      </h2>
      <p className="mb-6 leading-relaxed">
        Every DSPy program is built out of three things. A{" "}
        <strong>signature</strong> declares what the task
        is. A <strong>module</strong> decides how the LM is
        called to satisfy the signature. An{" "}
        <strong>optimizer</strong> takes a program, a
        dataset, and a metric, and produces a compiled
        version that scores higher on the metric. The
        design is deliberate: signatures are the interface,
        modules are the strategy, optimizers are the
        compiler.
      </p>
      <CodeBlock
        language="bash"
        filename="DSPy: the three primitives"
        code={`+-------------------------------------------------------+
|  Signature (typed, declarative)                       |
|                                                       |
|   class Answer(dspy.Signature):                       |
|     """Answer with a short citation."""               |
|     question: str = dspy.InputField()                 |
|     citation: str = dspy.OutputField()                |
|     answer:   str = dspy.OutputField()                |
+---------------------|---------------------------------+
                      v
+-------------------------------------------------------+
|  Module (strategy)                                    |
|                                                       |
|   dspy.Predict(Answer)          # one LM call         |
|   dspy.ChainOfThought(Answer)   # + reasoning field   |
|   dspy.ReAct(Answer, tools=[.]) # tool-calling loop   |
|   dspy.CodeAct(Answer, tools=[.]) # writes python     |
|   dspy.Refine(..., N=3)         # self-repair loop    |
+---------------------|---------------------------------+
                      v
+-------------------------------------------------------+
|  Optimizer (compiler)                                 |
|                                                       |
|   MIPROv2   -> instruction + few-shot search          |
|   SIMBA     -> feedback-driven prompt search          |
|   GEPA      -> reflective Pareto evolution            |
|   GRPO      -> RL on weights via Arbor                |
+-------------------------------------------------------+`}
      />
      <p className="mb-6 leading-relaxed">
        The signature is the smallest useful unit. It is a
        subclass of <code>pydantic.BaseModel</code>, which
        means every input and output field carries a type,
        a description, and any validation constraints you
        put on it. The adapter reads the signature at run
        time and turns it into the actual prompt sent to
        the model, so you never write the JSON schema, the
        role instruction, or the format block by hand. When
        the model swaps from Claude to GPT-5.5 to Gemini,
        the adapter changes the prompt, not you.
      </p>
      <p className="mb-6 leading-relaxed">
        Modules wrap common LM-calling patterns. A plain{" "}
        <code>dspy.Predict</code> is one LM call.{" "}
        <code>dspy.ChainOfThought</code> silently adds a{" "}
        <em>reasoning</em> field the model fills before the
        answer, which is the DSPy equivalent of a scratchpad.{" "}
        <code>dspy.ReAct</code> runs a tool-calling loop
        with a set of Python functions or MCP tools.{" "}
        <code>dspy.CodeAct</code> lets the model write
        Python that is executed in a sandbox and the result
        fed back. <code>dspy.Refine</code> runs the same
        module N times with a feedback signal so the model
        can fix its own output. Every module returns a{" "}
        <code>dspy.Prediction</code> object with named
        fields you can pass into another module.
      </p>
      <p className="mb-6 leading-relaxed">
        Optimizers are the piece that most teams underrate.
        They take a program that already works and rewrite
        the prompt text, pick the few-shot examples, and
        (with GRPO) fine-tune the model weights so the
        program scores higher on a metric. The metric is a
        Python function you write, which can be exact-match,
        an LLM-as-judge, a Pydantic validator, or anything
        else you can compute. The compiled program is a
        Python object you serialise to disk, ship in a
        container, and load in your serving process. No
        prompt string ever leaves your control.
      </p>

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        A first agent, end to end
      </h2>
      <p className="mb-6 leading-relaxed">
        The pattern below is the minimum viable DSPy agent:
        a signature, a ReAct module with two tools, and a
        MIPROv2 compile step that lifts it from a baseline
        of 62% on a small eval set to 84% on the same set,
        with no manual prompt edits.
      </p>
      <CodeBlock
        language="python"
        filename="src/agents/support_router.py"
        code={`import dspy
from dspy.teleprompt import MIPROv2

# 1. Configure the language model once, at the process boundary.
lm = dspy.LM("anthropic/claude-sonnet-5", max_tokens=2048)
dspy.configure(lm=lm)

# 2. Declare the task as a typed signature.
class RouteTicket(dspy.Signature):
    """Route a support ticket to the right queue and draft a reply."""

    ticket: str = dspy.InputField(desc="Raw customer message")
    queue: str = dspy.OutputField(
        desc="One of: billing, technical, account, refund",
    )
    priority: int = dspy.OutputField(
        desc="1 (low) to 5 (urgent)",
    )
    reply_draft: str = dspy.OutputField(
        desc="Two to four sentence draft reply to the customer",
    )

# 3. Two tools the agent can call.
def lookup_customer(email: str) -> dict:
    """Return plan tier and open incidents for a customer."""
    return crm.get(email)

def check_incident_board(area: str) -> list[str]:
    """Return active incidents in a product area."""
    return statuspage.active(area)

# 4. Compose a module. ReAct handles the tool-calling loop.
agent = dspy.ReAct(
    RouteTicket,
    tools=[lookup_customer, check_incident_board],
    max_iters=6,
)

# 5. Compile with MIPROv2 against a labelled eval set.
def score(pred, gold):
    return int(pred.queue == gold.queue) + int(pred.priority == gold.priority)

optimizer = MIPROv2(metric=score, auto="medium", num_threads=8)
compiled_agent = optimizer.compile(
    agent,
    trainset=trainset,   # list[dspy.Example]
    valset=valset,
)

# 6. Save the compiled program.
compiled_agent.save("artifacts/support_router.v3.json")
`}
      />
      <p className="mb-6 leading-relaxed">
        Four details are worth flagging. First,{" "}
        <code>dspy.configure</code> is process-global, but
        DSPy 3 made every setting thread-safe, so a request
        handler can override it per call. Second, the signature
        docstring becomes the system instruction, and every{" "}
        <code>desc=</code> on a field becomes a hint in the
        prompt. Write them as if a new engineer will read
        them. Third, the metric is where you spend design
        time; MIPROv2, SIMBA, and GEPA all optimise against
        whatever you put in it. Fourth, the compiled program
        is saved as JSON that includes the optimised
        instructions and demonstrations, not the source
        code, so you version it in your model registry, not
        in git alongside the source.
      </p>

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        The four optimizers in DSPy 3 and when to use each
      </h2>
      <p className="mb-6 leading-relaxed">
        DSPy 3 ships four production-ready optimizers, and
        picking the wrong one is the fastest way to waste a
        week of compute. The short version: MIPROv2 for
        most classifier and extraction tasks, SIMBA when
        you have a custom feedback signal, GEPA for
        agentic and multi-step programs with a scoring
        metric, and GRPO only when you need actual weight
        updates on an open-weights model.
      </p>
      <p className="mb-6 leading-relaxed">
        <strong>MIPROv2</strong> is a three-stage pipeline:
        bootstrap few-shot demonstrations by running the
        current program on the trainset, propose new
        instructions with a meta-LM, then use Bayesian
        optimization to pick the best combination on the
        valset. It works well on short, single-signature
        tasks where the output space is small (classification,
        entity extraction, structured summarisation). The{" "}
        <code>auto=</code> knob (<code>light</code>,{" "}
        <code>medium</code>, <code>heavy</code>) picks the
        number of trials for you. A typical medium run on
        a 100-example trainset is 30 to 60 minutes and 5 to
        20 dollars of API cost.
      </p>
      <p className="mb-6 leading-relaxed">
        <strong>SIMBA</strong> (Stochastic Introspective
        Mini-Batch Ascent) is the newer feedback-driven
        optimizer. Where MIPROv2 optimises a single scalar
        metric, SIMBA takes a callback that returns a
        natural-language critique of each example, and uses
        that critique to propose the next round of prompts.
        Reach for it when the failure modes are qualitative
        (&ldquo;the tone is too formal&rdquo;,{" "}
        &ldquo;the summary missed the second entity&rdquo;)
        and hard to reduce to a single number.
      </p>
      <p className="mb-6 leading-relaxed">
        <strong>GEPA</strong> (Genetic-Pareto) is the one to
        try first on any multi-step or agentic program in
        2026. The paper shows +13% over MIPROv2 and +20%
        over GRPO on aggregate, with 35 times fewer LM
        rollouts than GRPO. The mechanism is a Pareto tree
        of candidate prompts; each candidate is scored on a
        held-out slice, GEPA reflects on the trajectory of
        the best ones in natural language, and proposes new
        candidates by editing the winners. The starting
        point of a plain{" "}
        <code>dspy.ChainOfThought(&quot;question -&gt; answer&quot;)</code>{" "}
        on the MATH benchmark scores 67%; GEPA evolves a
        multi-step program that reaches 93% on the same
        benchmark. In our own client work, GEPA is what we
        run overnight on the eval set once the pipeline
        stabilises.
      </p>
      <p className="mb-6 leading-relaxed">
        <strong>GRPO</strong> is the RL fine-tuning path,
        implemented on top of the new Arbor library. Only
        pick it when you have an open-weights model
        (Llama, Qwen, DeepSeek) and a task where prompt
        changes are not enough. It needs GPUs, a reward
        model or exact-match metric, and thousands of
        rollouts. For most product teams, GEPA on a hosted
        frontier model is a better return per hour of
        engineering than GRPO on an open-weights model.
      </p>
      <CodeBlock
        language="python"
        filename="src/agents/optimize_with_gepa.py"
        code={`import dspy
from dspy.teleprompt import GEPA

# Reuse the ReAct agent from above.
agent = dspy.ReAct(RouteTicket, tools=[...], max_iters=6)

# The metric can now return a rich feedback dict, not just a number.
def metric_with_feedback(gold, pred, trace=None, pred_name=None,
                         pred_trace=None):
    score = int(pred.queue == gold.queue)
    feedback = []
    if pred.queue != gold.queue:
        feedback.append(
            f"Queue was {pred.queue!r}, gold was {gold.queue!r}. "
            f"Look for the phrase {gold.hint!r} in the ticket."
        )
    if pred.priority != gold.priority:
        feedback.append(
            f"Priority was {pred.priority}, gold was {gold.priority}. "
            f"An outage in the customer's plan tier raises the priority."
        )
    return dspy.Prediction(score=score, feedback="; ".join(feedback))

gepa = GEPA(
    metric=metric_with_feedback,
    auto="medium",             # or "light" / "heavy"
    reflection_lm=dspy.LM("openai/gpt-5.5", max_tokens=8192),
    num_threads=16,
)

optimized_agent = gepa.compile(
    agent,
    trainset=trainset,
    valset=valset,
)
optimized_agent.save("artifacts/support_router.gepa.json")
`}
      />
      <p className="mb-6 leading-relaxed">
        The subtle difference from MIPROv2 is the metric
        signature. GEPA passes back rich natural-language
        feedback per example, which the reflection LM uses
        to propose the next prompt. That is where the
        &ldquo;reflective&rdquo; in the paper title comes
        from. It is also why GEPA does so well on agentic
        pipelines: the trajectory of a ReAct or CodeAct
        program is exactly the kind of thing an LM is good
        at critiquing in natural language.
      </p>

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        Structured outputs with adapters and Pydantic
      </h2>
      <p className="mb-6 leading-relaxed">
        Structured output is where every serious agent
        pipeline ends up, and DSPy 3 finally makes it
        painless. Every signature field is a Pydantic
        FieldInfo, so you can declare any Pydantic type as
        an output (nested models, enums, lists, discriminated
        unions) and DSPy handles the prompt and the parsing.
        The adapter layer converts the type into either a
        JSON schema, a BAML-style commented Pydantic
        pseudo-code block, or the native structured-output
        API of the underlying model (OpenAI response_format,
        Anthropic tool use).
      </p>
      <CodeBlock
        language="python"
        filename="src/agents/typed_extraction.py"
        code={`import dspy
from pydantic import BaseModel, Field
from typing import Literal

class LineItem(BaseModel):
    sku: str
    quantity: int = Field(gt=0)
    unit_price_cents: int = Field(ge=0)

class Invoice(BaseModel):
    supplier: str
    invoice_number: str
    total_cents: int
    currency: Literal["USD", "EUR", "GBP"]
    line_items: list[LineItem]

class ExtractInvoice(dspy.Signature):
    """Extract the invoice fields from the OCR text."""

    ocr_text: str = dspy.InputField()
    invoice: Invoice = dspy.OutputField()

# BAMLAdapter renders the Pydantic type as commented pseudo-code,
# which uses fewer tokens than raw JSON schema for nested types.
dspy.configure(
    lm=dspy.LM("openai/gpt-5.5-mini"),
    adapter=dspy.BAMLAdapter(),
)

extract = dspy.Predict(ExtractInvoice)
result = extract(ocr_text=raw_ocr)
# result.invoice is an Invoice instance, already validated.
`}
      />
      <p className="mb-6 leading-relaxed">
        The BAMLAdapter is the one to reach for when the
        output schema is nested and JSONAdapter produces a
        wall of raw JSON schema in the prompt. In our
        measurement, switching from JSONAdapter to
        BAMLAdapter on the invoice schema above cut the
        prompt from 1,800 tokens to 620 tokens, with no
        change in extraction quality. On a 100k-invoice
        batch that is a real bill reduction.
      </p>

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        Deploying: FastAPI, asyncify, streamify, MLflow 3
      </h2>
      <p className="mb-6 leading-relaxed">
        DSPy 3 has a stable deployment story that fits how
        Python services already ship. Two patterns cover
        almost every production use: a FastAPI service that
        wraps the compiled program with{" "}
        <code>dspy.asyncify</code> and{" "}
        <code>dspy.streamify</code>, or an MLflow-served
        model that hands the same job to Databricks Model
        Serving, SageMaker, or a self-hosted MLflow server.
      </p>
      <CodeBlock
        language="python"
        filename="app/main.py"
        code={`from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
import dspy
from dspy.utils.streaming import streaming_response

app = FastAPI(title="Support Router", version="3.0")

lm = dspy.LM("anthropic/claude-sonnet-5", max_tokens=2048)
dspy.configure(lm=lm, async_max_workers=16)

# Load the compiled artefact once at startup.
agent = dspy.ReAct(RouteTicket, tools=[lookup_customer, check_incident_board])
agent.load("artifacts/support_router.gepa.json")

# asyncify runs the sync program in a worker thread and returns a coroutine.
async_agent = dspy.asyncify(agent)

# streamify wraps the async program so intermediate tokens can be streamed.
stream_agent = dspy.streamify(async_agent)

class Ticket(BaseModel):
    text: str

@app.post("/route")
async def route(ticket: Ticket):
    try:
        pred = await async_agent(ticket=ticket.text)
        return pred.toDict()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))

@app.post("/route/stream")
async def route_stream(ticket: Ticket):
    stream = stream_agent(ticket=ticket.text)
    return StreamingResponse(
        streaming_response(stream),
        media_type="text/event-stream",
    )
`}
      />
      <p className="mb-6 leading-relaxed">
        The default worker pool for <code>asyncify</code> is
        eight threads. On any service that handles more than
        a handful of concurrent requests, set{" "}
        <code>async_max_workers</code> explicitly in the
        <code>dspy.configure</code> call; otherwise a burst
        will queue behind the pool. The streaming path is
        wired to Server-Sent Events out of the box, which is
        what modern browser clients and the Vercel AI SDK
        expect on the wire. If you need the raw stream
        events (per-token deltas, tool-call boundaries, module
        status), <code>streamify</code> yields them as
        typed dictionaries you can transform before sending.
      </p>
      <p className="mb-6 leading-relaxed">
        The MLflow 3 path is the one to pick when you want
        the compiled program, the training data, the metric
        code, and the evaluation results tracked as a single
        registered model. The <code>mlflow.dspy</code> flavor
        logs the DSPy program as a PythonModel, wraps it in
        FastAPI, and gives you the standard MLflow serve
        command. The tracing integration then records every
        LM call, every tool invocation, and every module
        boundary as an OpenTelemetry span, which shows up
        in the MLflow UI and any OTel-compatible backend
        (Datadog, Honeycomb, Grafana Tempo).
      </p>
      <CodeBlock
        language="python"
        filename="scripts/register_with_mlflow.py"
        code={`import dspy, mlflow

mlflow.set_tracking_uri("databricks")
mlflow.set_experiment("/Shared/support_router")

# Enable DSPy autologging: every dspy.LM call becomes a span.
mlflow.dspy.autolog(
    log_traces=True,
    log_traces_from_compile=True,
)

class SupportRouter(dspy.Module):
    def __init__(self):
        super().__init__()
        self.route = dspy.ReAct(RouteTicket, tools=[...])
        self.route.load("artifacts/support_router.gepa.json")

    def forward(self, messages):
        return self.route(ticket=messages[-1]["content"])

with mlflow.start_run() as run:
    mlflow.dspy.log_model(
        SupportRouter(),
        artifact_path="model",
        task="llm/v1/chat",
        input_example={
            "messages": [
                {"role": "user", "content": "My April invoice is wrong."}
            ],
        },
        registered_model_name="support_router",
    )

# On the serving side:
#   mlflow models serve -m models:/support_router/Production -p 8000
`}
      />

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        The JetBlue and Databricks case study
      </h2>
      <p className="mb-6 leading-relaxed">
        The most useful public case study on DSPy in
        production is the JetBlue write-up Databricks
        published in mid-2024. JetBlue had a multi-stage
        LLM pipeline for a predictive-maintenance chatbot,
        with a classifier stage, a retrieval-augmented
        answer stage, and a follow-up question stage. The
        original build was a hand-tuned LangChain pipeline
        with a Llama 2 70B model on Databricks Model
        Serving and a Databricks Vector Search index.
        Every model swap, every schema change, and every
        eval regression required a human to rewrite prompts
        by hand across three stages.
      </p>
      <p className="mb-6 leading-relaxed">
        The DSPy port replaced the prompt strings with
        signatures, wrapped each stage in a module, and
        compiled the pipeline against an LLM-as-judge metric
        on a labelled set of past tickets. The reported
        results: a 2x faster deployment cycle compared to
        the LangChain baseline, elimination of manual
        prompt engineering across the pipeline, and the
        ability to re-compile the whole system whenever
        the underlying model changed. The same team went on
        to use DSPy for customer-feedback classification
        with the same architecture.
      </p>
      <p className="mb-6 leading-relaxed">
        Two operational lessons from that build carry over
        to almost every DSPy production project we have
        run. First, the metric is the artefact that matters
        most. Every hour spent making the LLM-as-judge
        metric closer to the human judgement pays off many
        times in optimizer runs. Second, the compiled
        program has to be versioned separately from the
        source code, in the model registry, not in git.
        Recompiling with a new model or a new metric
        produces a new artefact, and rollback should be a
        model-registry swap, not a git revert.
      </p>

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        DSPy vs LangChain vs LlamaIndex in 2026
      </h2>
      <p className="mb-6 leading-relaxed">
        These three frameworks solve overlapping but
        distinct problems, and the industry has largely
        stopped arguing about which one wins. The short
        read: LlamaIndex owns document ingestion and
        retrieval. LangChain and LangGraph own the wide
        catalogue of tool integrations and the flexible
        orchestration graph. DSPy owns the compilable,
        optimisable core of the reasoning pipeline. Most
        production stacks we see in 2026 combine two of the
        three.
      </p>
      <ul className="mb-6 list-disc space-y-2 pl-6">
        <li>
          <strong>DSPy strengths</strong>: prompts as
          learnable parameters, typed signatures, four
          strong optimizers, MLflow-native tracing, thread-
          safe async and streaming, small surface area to
          read and audit. Best when you have a labelled
          eval set and a clear metric.
        </li>
        <li>
          <strong>DSPy weaknesses</strong>: the approach is
          unfamiliar to most Python engineers, the community
          catalogue is thinner than LangChain&rsquo;s, the
          optimizer step needs real training data, and the
          bill for a heavy GEPA or GRPO run is non-trivial.
          Prompt behaviour can shift when the model changes,
          so re-compilation is part of the release process.
        </li>
        <li>
          <strong>LangChain strengths</strong>: the widest
          set of ready-made tool and retriever integrations,
          the LangGraph state machine for long-running
          workflows, LangSmith for tracing and evaluation.
          Ships prototypes fastest.
        </li>
        <li>
          <strong>LlamaIndex strengths</strong>: 160+ data
          connectors, the strongest indexing and reranking
          primitives, first-class hybrid search. Use when
          retrieval quality is the primary success metric.
        </li>
      </ul>
      <p className="mb-6 leading-relaxed">
        On new client engagements we start with a
        LangChain or LangGraph prototype for exploration,
        because the tool catalogue and the state graph get
        you to a working demo in a week. Once the shape of
        the pipeline is stable and a labelled eval set
        exists, the critical reasoning steps move to DSPy
        so the metric can drive the prompts. LlamaIndex
        stays in the ingestion layer. This is not a
        theoretical split; it is what the JetBlue,
        Databricks, and Shopify teams describe in their
        public write-ups.
      </p>

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        Where DSPy is not the right choice
      </h2>
      <p className="mb-6 leading-relaxed">
        The honest answer is: DSPy is the wrong pick when
        you have no eval set, no clear metric, and no
        appetite to build one. The whole value of the
        framework is the optimizer step, and the optimizer
        needs a training set and a scoring function. A team
        that ships a prompt today, checks it works on three
        examples, and ships tomorrow will not get its
        money back from a MIPROv2 or GEPA run. That is
        fine; ship the prompt, and come back to DSPy when
        the pipeline stops meeting the accuracy bar.
      </p>
      <p className="mb-6 leading-relaxed">
        The other case is real-time single-shot workloads
        where the reasoning is trivial and latency is the
        constraint. DSPy adds a small overhead per call
        (adapter formatting, module dispatch, prediction
        object construction) that is invisible on a
        multi-second agent trace and visible on a 50ms
        classification hot path. For those, a plain
        function-call to the model API is simpler and
        faster.
      </p>
      <p className="mb-6 leading-relaxed">
        A third case is safety-critical output where the
        cost of a wrong answer is a lawsuit or a shipping
        pause. DSPy can lift accuracy from the mid-80s to
        the mid-90s on many tasks, and that gap is real,
        but it is not full validation. Those pipelines
        still need a human review layer or a deterministic
        checker on top; DSPy makes them cheaper to build,
        not safer on their own.
      </p>

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        Where the framework is going in 2026 and beyond
      </h2>
      <p className="mb-6 leading-relaxed">
        Three threads are worth watching. The first is{" "}
        <strong>program synthesis on top of prompt
        optimization</strong>. <code>dspy.Flex</code>, added
        in 3.3, lets GEPA change the shape of the program
        (add a retrieval step, remove a refine loop, swap a
        module) not just the prompts inside a fixed shape.
        The natural end state is a compiler that starts from
        a signature and an eval set, and returns a full
        pipeline. Early results in the Cerebras and Stanford
        forks suggest this is closer than it looks.
      </p>
      <p className="mb-6 leading-relaxed">
        The second is <strong>MCP as the tool interface</strong>.
        DSPy 3.2 added a first-class MCP client, so any
        module can call any MCP server as a tool. That
        cleanly separates the reasoning pipeline (DSPy) from
        the tool surface (MCP), which mirrors how Claude,
        ChatGPT, and Cursor are converging. The upside is
        a compiled DSPy program can point at a new MCP
        server without a rewrite. The downside is prompt-
        injection risk from untrusted MCP servers moves
        into the DSPy runtime; our advice is the same as
        for any other agent framework, keep every MCP
        server on an allowlist and treat tool output as
        untrusted input.
      </p>
      <p className="mb-6 leading-relaxed">
        The third is <strong>the GEPA-style feedback loop
        moving into the runtime</strong>. Today, GEPA
        optimises against a static training set; in the
        research forks, teams are running the reflection
        step on live production traces, with a human or a
        stronger judge model providing the feedback signal.
        The end state is a DSPy program that keeps its
        metric high as the traffic shifts, without a
        release. That is not the default in 3.3, but it is
        the direction the framework is pointed.
      </p>

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        Conclusion: when to reach for DSPy
      </h2>
      <p className="mb-6 leading-relaxed">
        DSPy is the answer to a specific problem. You have
        an LLM pipeline that works, you have a labelled
        eval set with a scoring metric, and you want the
        prompts to be produced by a compiler instead of a
        person. On that problem, in mid-2026, DSPy 3 is
        the strongest option. The signature-and-module
        model gives you a program you can read; MIPROv2,
        SIMBA, and GEPA give you a compiler that beats
        hand-written prompts; the MLflow 3 integration
        gives you the tracing and registry story a
        production system needs.
      </p>
      <p className="mb-6 leading-relaxed">
        The pattern that has worked for us on client work
        is: start with a prototype in whatever framework
        the team already knows (usually LangChain or
        LangGraph), get to a working eval set as fast as
        possible, and only then port the reasoning core to
        DSPy so a nightly compile step keeps the metric
        moving up. Once the JetBlue-style lesson lands
        (the metric is the artefact, not the prompt), the
        rest of the framework starts to earn its place.
        That is the state of DSPy in mid-2026: the
        research is settled, the framework is stable, and
        the production adopters are naming themselves in
        blog posts.
      </p>

      <h2 className="mb-4 mt-10 text-3xl font-bold text-white">
        Further reading
      </h2>
      <ul className="mb-6 list-disc space-y-2 pl-6">
        <li>
          <a
            href="https://arxiv.org/abs/2310.03714"
            className="font-semibold text-primaryColor hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            DSPy: Compiling Declarative Language Model Calls
            into Self-Improving Pipelines (Khattab et al.,
            October 2023)
          </a>
          {" "}- the original paper that introduced
          signatures, modules, and the compiler-based
          approach to prompting.
        </li>
        <li>
          <a
            href="https://arxiv.org/abs/2507.19457"
            className="font-semibold text-primaryColor hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            GEPA: Reflective Prompt Evolution Can Outperform
            Reinforcement Learning (Agrawal et al., July
            2025, ICLR 2026 Oral)
          </a>
          {" "}- the paper that shows the +13% over MIPROv2
          and +20% over GRPO numbers, plus the mechanism of
          reflective Pareto evolution.
        </li>
        <li>
          <a
            href="https://github.com/stanfordnlp/dspy/releases/tag/3.0.0"
            className="font-semibold text-primaryColor hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            DSPy 3.0.0 release notes (August 12, 2025)
          </a>
          {" "}- the full changelog for the 3.0 line, with
          the four optimizers, adapters, multi-modal types,
          and MLflow 3 integration.
        </li>
        <li>
          <a
            href="https://dspy.ai/production/"
            className="font-semibold text-primaryColor hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            DSPy production guide
          </a>
          {" "}- the official deployment reference, with
          thread-safety, async, MLflow tracing, and the
          list of production adopters.
        </li>
        <li>
          <a
            href="https://github.com/stanfordnlp/dspy/blob/main/docs/docs/tutorials/deployment/index.md"
            className="font-semibold text-primaryColor hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            DSPy deployment tutorial (FastAPI, asyncify,
            streamify, MLflow)
          </a>
          {" "}- the source-of-truth code samples for the
          FastAPI and MLflow paths.
        </li>
        <li>
          <a
            href="https://www.databricks.com/blog/optimizing-databricks-llm-pipelines-dspy"
            className="font-semibold text-primaryColor hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            Optimizing Databricks LLM Pipelines with DSPy
            (Databricks Blog, 2024)
          </a>
          {" "}- the JetBlue case study with the 2x faster
          deployment number and the Model Serving plus
          Vector Search architecture.
        </li>
        <li>
          <a
            href="https://mlflow.org/docs/latest/genai/flavors/dspy/"
            className="font-semibold text-primaryColor hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            MLflow DSPy flavor reference
          </a>
          {" "}- the tracing autologging, model logging, and
          serving reference for the MLflow integration.
        </li>
        <li>
          <a
            href="https://dspy.ai/tutorials/gepa_ai_program/"
            className="font-semibold text-primaryColor hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            Reflective Prompt Evolution with GEPA (DSPy
            tutorial)
          </a>
          {" "}- the code walkthrough for compiling a
          program with GEPA, including the feedback metric
          signature.
        </li>
        <li>
          <a
            href="/articles/langgraph-production-agents-2026"
            className="font-semibold text-primaryColor hover:underline"
          >
            LangGraph in production 2026
          </a>
          {" "}- the deeper read on the state-graph
          framework that pairs well with DSPy for the
          orchestration layer.
        </li>
        <li>
          <a
            href="/articles/agent-evaluation-observability-2026"
            className="font-semibold text-primaryColor hover:underline"
          >
            Agent evaluation and observability in 2026
          </a>
          {" "}- the tracing and eval story that DSPy leans
          on through the MLflow 3 integration.
        </li>
        <li>
          <a
            href="/articles/context-engineering-ai-agents-2026"
            className="font-semibold text-primaryColor hover:underline"
          >
            Context engineering for AI agents in 2026
          </a>
          {" "}- the deeper read on how signatures and
          adapters fit into the broader context-engineering
          discipline.
        </li>
        <li>
          <a
            href="/articles/mcp-production-ai-integrations-2026"
            className="font-semibold text-primaryColor hover:underline"
          >
            MCP in production 2026
          </a>
          {" "}- the protocol DSPy 3.2 adopted as the tool
          interface for its modules.
        </li>
      </ul>
    </div>
  );
}
